### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Yunming01** [herolab-uga/indoor-rssi-mobile-robot#1]
Can you tell me the download website of this dataset？Thanks

**Comment by ramviyas** [comment]
The github repo master itself has the files of the dataset in the datalog format (CSV format). The README file contains the structure of the data within this datalog. You can download and read this file in excel or any script that can parse csv data.
Example: Dataset 1
https://github.com/herolab-uga/indoor-rssi-mobile-robot/blob/master/Dataset1.datalog
